### ISSUE TITLE
`left-pad@0.0.3` dependency no longer exists in npm

### ISSUE THREAD

**Issue by mridgway** [lydell/line-numbers#1]
`left-pad` seems to have been deleted from the npm registry: https://www.npmjs.com/package/left-pad

**Comment by mridgway** [comment]
Seems to have been a transient issue with the registry. The 404 seems to have only lasted 10 minutes or so.

**Comment by kayakyakr** [comment]
The version of left-pad that's on npm is now 0.0.9, not 0.0.3 required by line-numbers.

**Comment by mridgway** [comment]
You're right, that version no longer exists.

**Comment by jonathanong** [comment]
just emailed him. hopefully he's awake!

**Comment by aidos** [comment]
I'm new to this whole npm world and I'm trying to install babelify tonight so this is a bit of a showstopper.

My workaround for the moment is to hack `~/.npm/line-numbers/0.2.0/package/package.json` and `~/.npm/registry.npmjs.org/line-numbers/.cache.json` to change `left-pad":"0.0.3` to `left-pad":"0.0.9"`

**Comment by jasisk** [comment]
[FYI: this was a political statement](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.3c6g1f1jk).

**Comment by kayakyakr** [comment]
That's super lame. I say ostracize that dude from the Internet.

Thanks to @azer (https://github.com/azer/left-pad) for taking ownership and getting a compatible version in there.

**Comment by macklevine** [comment]
https://twitter.com/seldo/status/712414588281552900

I have mixed feelings about this but it sure makes my life easier

**Comment by lydell** [comment]
What a mess to wake up to! I'm here and alive, but busy at the moment :)

Since `npm install line-numbers` seems to work again (I just tried it), I'll come back in <12 hours and fix things.

**Comment by lydell** [comment]
Step 1 is done: I've submitted babel/babel#3441

**Comment by lydell** [comment]
Step 2 is done: Update to left-pad ^1.0.1. Published on npm as 0.2.1.

Step 3 is done: Deprecated this rather silly package.
